

version: '3.8'

services:
  glue:
    image: amazon/aws-glue-streaming-libs:glue_streaming_libs_4.0.0_image_01
    container_name: glue_container
    environment:
      - PYSPARK_PYTHON=python3
      - PYSPARK_DRIVER_PYTHON=python3
    volumes:
      - ./glue:/home/glue_user/workspace/
    ports:
      - "4040:4040" 
      - "18080:18080"
    stdin_open: true
    tty: true

  postgres:
    image: postgres:13
    container_name: postgres_container
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: my_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  postgres_data:

